### ISSUE TITLE
What does advection scheme 555 do?

### ISSUE THREAD

**Issue by goord** [goord/dales#10]
If it has the same result as scheme 55 but is just faster, it should replace that scheme IMO.

**Comment by fjansson** [comment]
555 is indeed supposed to have the same results as 55. I decided to start a new implementation rather than changing the old one, since the modifications are extensive and one may need to switch back and forth for testing. I propose to keep them this way for a while longer.

Btw, I found an off-by-one bug in 555 yesterday when gathering improvement proposals for the official dales, I'll fix it in our fork too. After this fix, the results of the two schemes seem very close.

**Comment by fjansson** [comment]
The off-by-one bug is fixed now, in fcf8019.
