### ISSUE TITLE
Rename OMUSE Dales grid names

### ISSUE THREAD

**Issue by goord** [goord/dales#11]
- ```grids``` should be ```fields```
- ```nudging``` should be ```nudging_profiles```
- ```forcings``` should be ```forcing_profiles```

This all has to be changed in

1. The OMUSE interface code
2. The examples in OMUSE and python-note
3. The examples in https://github.com/CloudResolvingClimateModeling/dales-omuse-examples
4. The paper table
5. The paper code snippets

**Comment by fjansson** [comment]
more renaming: forcings[:].tendency_THL -> forcings[:].THL etc

**Comment by goord** [comment]
More renaming:

- Pressure should be denoted with ```P```, modified pressure with ```pi```
- Rain should be denoted with ```QR```
- Replace ```LWP```, ```TWP``` and ```RWP``` with ```QL```, ```QT``` and ```QR```

**Comment by goord** [comment]
I guess we want to remove the function
```python
DalesInterface.get_field(self, field, imin=1, imax=None, jmin=1, jmax=None, kmin=1, kmax=None)
DalesInterface.set_field(self, field, a, imin=1, jmin=1, kmin=1):
```
because they are essentially duplicated by the grid interface

**Comment by goord** [comment]
Furthermore it may be useful to include the paper table containing this information in the Sphinx documentation as well

**Comment by fjansson** [comment]
> Replace LWP, TWP and RWP with QL, QT and QR

This may be confusing, since the LWP, TWP, RWP are integrated over the vertical direction (liquid water path etc), while QL, QT, QR are generally just local values.

About removing get_field, set_field - they are in `Dales`, not `DalesInterface`, right? 
I agree they could go. Then maybe `get_profile()` can be removed as well?
The `get_profile_U` etc are in principle also replaced by the grid interface, but 1) we still use them in sp-coupler, 2) The grid interface async functionality isn't quite there yet, while these functions work asynchronously. So they should stay for now.

**Comment by goord** [comment]
> > Replace LWP, TWP and RWP with QL, QT and QR
> 
> This may be confusing, since the LWP, TWP, RWP are integrated over the vertical direction (liquid water path etc), while QL, QT, QR are generally just local values.
> 
Ok, but the profiles are also averaged and still denoted with the same letter. But I agree that the vertical integration should be clearly distinguishable from say a the lowest full level level slice

**Comment by fjansson** [comment]
yes if the grid name would indicate vertical integration, I'd be fine with naming them QL etc. But now they are in the surface_fields grid, so it's not clear.

**Comment by goord** [comment]
Ok let's stick to the current naming scheme, I don't feel like inventing yet another grid. I will just add extra entries to the table of variables
